
import './legalide.scss'
import './images/icons/fb-icon.png'
import './images/icons/areas-icon-1.png'
import './images/icons/areas-icon-2.png'
import './images/icons/areas-icon-3.png'
import './images/icons/cart-icon.png'
import './images/icons/ig-icon.png'
import './images/icons/phone-icon.png'
import './images/icons/pin-icon.png'
import './images/icons/search-icon.png'
import './images/icons/send-icon.png'
import './images/icons/twitter-icon.png'
import './images/icons/youtube-icon.png'

import './images/advice-card-1.png'
import './images/advice-card-2.png'
import './images/advice-card-3.png'
import './images/advice-card-4.png'
import './images/about-bg.jpg'
import './images/clients-logo-1.png'
import './images/clients-logo-2.png'
import './images/clients-logo-3.png'
import './images/clients-logo-4.png'
import './images/clients-logo-5.png'
import './images/clients-logo-6.png'
